#!/bin/sh

set -eu

if [ $# -ne 1 ]; then
  echo "usage: avenv VENV-DIR"
  exit 1
fi

venv=$(realpath "$1")

mkdir "$venv"
mkdir "$venv/bin"
mkdir "$venv/bin/rootfs"

# ubuntu 18.04 currently
# FIXME: use https or check the hash or so!
ROOTFS_URL="http://cdimage.ubuntu.com/ubuntu-base/releases/18.04/release/ubuntu-base-18.04-base-amd64.tar.gz"

cd "$venv/bin/rootfs"
curl -'#' -L --fail $ROOTFS_URL | tar --no-same-owner --exclude dev -xzf -
cd - > /dev/null

# we excluded it, but need an empty directory for the mount
mkdir "$venv/bin/rootfs/dev"

curl -'#' -L --fail "https://github.com/ihucos/bchroot/raw/master/bchroot" > $venv/bchroot
chmod 744 $venv/bchroot

rm -f $venv/bin/rootfs/etc/resolv.conf

# redunancy, bchroot already attempts and bind mount
cp /etc/resolv.conf $venv/bin/rootfs/etc/resolv.conf

echo 'APT::Sandbox::User "root";' > $venv/bin/rootfs/etc/apt/apt.conf.d/90stayroot

echo "#/bin/sh
cd $venv/bin/rootfs
find ./usr/local/bin ./usr/bin ./bin ./usr/local/sbin ./usr/sbin ./sbin 2> /dev/null \
| xargs -n 1 basename | sort | uniq \
| xargs -I{} sh -c \"ln -f $venv/bchroot $venv/bin/{}\"
" > "$venv/bin/avenv-update"
chmod +x "$venv/bin/avenv-update"

"$venv/bchroot" "$venv/bin/rootfs" sh -ec '
apt-get update
apt-get install -y --no-install-recommends curl python3-pip
j 2>&1 | while read l
do 
  echo "avenv: $l"
done

"$venv/bin/avenv-update"

echo "
alias python=$venv/bin/python
alias pip=$venv/bin/pip
alias python3=$venv/bin/python3
alias pip3=$venv/bin/pip3

PS1=\"($(basename "$venv")) "'$'"PS1\"

deactivate(){
  unalias python
  unalias python3
  unalias pip
  unalias pip3
  PS1=\""'$'"(echo \""'$'"PS1\" | cut -d ' ' -f2)\"
  unset -f deactivate
}
" > "$venv/bin/activate"
