#!/bin/sh

set -eu


# ubuntu 18.04 currently
# FIXME: use https or check the hash or so!
ROOTFS_URL="http://cdimage.ubuntu.com/ubuntu-base/releases/18.04/release/ubuntu-base-18.04-base-amd64.tar.gz"


if [ $# -ne 1 ]; then
  echo "usage: avenv VENV-DIR"
  exit 1
fi

venv=$(realpath "$1")

mkdir "$venv"
mkdir "$venv/bin"
mkdir "$venv/bin/rootfs"


curl -'#' -L --fail "https://github.com/ihucos/bchroot/releases/download/0.3/bchroot" > $venv/bchroot
chmod 744 $venv/bchroot

curl -'#' -L --fail "https://github.com/ihucos/bchroot/releases/download/0.3/zudo" > $venv/zudo
chmod 744 $venv/zudo

cd "$venv/bin/rootfs"
curl -'#' -L --fail $ROOTFS_URL | $venv/zudo tar --exclude dev -xzf -
cd - > /dev/null

# we excluded it, but need an empty directory for the mount
mkdir "$venv/bin/rootfs/dev"

# redunancy, bchroot already attempts and bind mount
rm -f $venv/bin/rootfs/etc/resolv.conf
cp /etc/resolv.conf $venv/bin/rootfs/etc/resolv.conf

echo "#/bin/sh
cd $venv/bin/rootfs
find ./usr/local/bin ./usr/bin ./bin ./usr/local/sbin ./usr/sbin ./sbin 2> /dev/null \
| xargs -n 1 basename | sort | uniq \
| xargs -I{} sh -c \"ln -f $venv/bchroot $venv/bin/{}\"
" > "$venv/bin/avenv-update"
chmod +x "$venv/bin/avenv-update"

"$venv/bin/avenv-update"
"$venv/bin/apt-get" update
"$venv/bin/apt-get" install -y --no-install-recommends curl python3-pip
"$venv/bin/avenv-update"

echo "
alias python=$venv/bin/python
alias pip=$venv/bin/pip
alias python3=$venv/bin/python3
alias pip3=$venv/bin/pip3

PS1=\"($(basename "$venv")) "'$'"PS1\"

deactivate(){
  unalias python
  unalias python3
  unalias pip
  unalias pip3
  PS1=\""'$'"(echo \""'$'"PS1\" | cut -d ' ' -f2)\"
  unset -f deactivate
}
" > "$venv/bin/activate"
